DECLARE @MainTableColumnsMaster AS TABLE
(
   ColumnName        VARCHAR(76) NOT NULL UNIQUE
  ,DisplayColumnName VARCHAR(76) NOT NULL
  ,DataType        VARCHAR(8) NOT NULL
);
INSERT INTO @MainTableColumnsMaster(ColumnName,DisplayColumnName,DataType) VALUES
 ('GEP_DATAID','GEP DATA ID','bigint')
,('UNIQUEID','Unique ID','nvarchar')
,('INVOICE_DOCUMENT_TYPE','Invoice Document Type','nvarchar')
,('INVOICE_POSTING_KEY','Invoice Posting Key','nvarchar')
,('INVOICE_DOCUMENT_NUMBER','Invoice Document Number','nvarchar')
,('INVOICE_NUMBER','Invoice Number','nvarchar')
,('INVOICE_LINE_NUMBER','Invoice Line Number','nvarchar')
,('INVOICE_DISTRIBUTION_LINE_NUMBER','Invoice Line Distribution number','nvarchar')
,('INVOICE_NUMBER_2','Invoice Number 2','nvarchar')
,('INVOICE_NUMBER_3','Invoice Number 3','nvarchar')
,('INVOICE_VOUCHER_NUMBER','Invoice Voucher Number','nvarchar')
,('INVOICE_VOUCHER_LINE_NUMBER','Invoice Voucher Line Number','nvarchar')
,('INVOICE_JOURNAL_NUMBER','Invoice Journal Number','nvarchar')
,('INVOICE_LINE_TYPE','Invoice Line Type','nvarchar')
,('INVOICE_PAYMENT_METHOD','Invoice Payment Method','nvarchar')
,('INVOICE_CREATION_DATE','Invoice Creation Date','date')
,('INVOICE_RECEIPT_DATE','Invoice Receipt Date','date')
,('INVOICE_PERIOD_ID','Invoice Period ID','nvarchar')
,('INVOICE_POSTING_DATE','Invoice Posted Date','date')
,('INVOICE_ACCOUNTING_DATE','Invoice Accounting Date','date')
,('INVOICE_PAID_DATE','Invoice Paid Date','date')
,('INVOICE_LINE_AMOUNT_NORMALIZED','Invoice Line Amount Normalized','float')
,('PO_UNIT_PRICE_LOCAL','PO Unit Price Local','float')
,('INVOICE_LINE_AMOUNT_CURRENCY','Invoice Line Amount Currency','nvarchar')
,('INVOICE_DEBIT_CREDIT_INDICATOR','Invoice Debit Credit Indicator','nvarchar')
,('INVOICE_UNIT_PRICE_NORMALIZED','Invoice Unit Price Normalized','float')
,('INVOICE_LINE_AMOUNT_LOCAL','Invoice Line Amount Local','float')
,('INVOICE_UNIT_PRICE_CURRENCY','Invoice Unit Price Currency','nvarchar')
,('INVOICE_QUANTITY','Invoice Quantity','float')
,('INVOICE_UOM','Invoice UOM','nvarchar')
,('INVOICE_LINE_DESCRIPTION','Invoice Description','nvarchar')
,('INVOICE_LINE_DESCRIPTION_2','Invoice Description 2','nvarchar')
,('INVOICE_CREATED_BY','Invoice Created By','nvarchar')
,('INVOICE_APPROVED_BY','Invoice Approved By','nvarchar')
,('INVOICE_LANGUAGE_KEY','Invoice Language','nvarchar')
,('INVOICE_STATUS','Invoice Status','nvarchar')
,('INVOICE_TYPE','Invoice Type','nvarchar')
,('SHIPPING_CODE','Shipping Code','nvarchar')
,('SHIPPING_MODE_TYPE','Shipping Mode Type','nvarchar')
,('SHIPPING_TYPE','Shipping Type','nvarchar')
,('INVOICE_DIRECT_INDIRECT_INDICATOR','Direct Indirect Indicator','nvarchar')
,('CAPEX_OPEX_INDICATOR','Capex Opex Indicator','nvarchar')
,('DOMESTIC_INTERNALTIONAL_INDICATOR','Domestic International Indicator','nvarchar')
,('GEP_NORM_INVOICE_UNIT_PRICE_USD','GEP Normalized Invoice Unit Price (USD)','float')
,('GEP_NORM_INVOICE_UNIT_PRICE_EUR','GEP Normalized Invoice Unit Price (EUR)','float')
,('GEP_NORM_INVOICE_QUANTITY','GEP Normalized Invoice Quanity','float')
,('GEP_NORM_INVOICE_UOM','GEP Normalized Invoice UOM','nvarchar')
,('EXCH_MONTH','GEP Currecy Exchange Month','nvarchar')
,('EXCH_YEAR','GEP Currecy Exchange Year','nvarchar')
,('EXCH_RATE','GEP Currecy Exchange Rate','float')
,('GEP_NORM_SPEND_USD','GEP Normalized Spend (USD)','float')
,('GEP_NORM_SPEND_USD_WITHOUT_TAX','GEP Normalized Spend (USD) Without Tax','float')
,('GEP_NORM_SPEND_EUR','GEP Normalized Spend (EUR)','float')
,('GEP_NORM_SPEND_EUR_WITHOUT_TAX','GEP Normalized Spend (EUR) Without Tax','float')
,('GEP_NORM_SPEND_GBP','GEP Normalized Spend (GBP)','float')
,('GEP_NORM_SPEND_AUD','GEP Normalized Spend (AUD)','float')
,('GEP_NORM_SPEND_CAD','GEP Normalized Spend (CAD)','float')
,('GEP_NORM_SPEND_CNY','GEP Normalized Spend (CNY)','float')
,('GEP_NORM_SPEND_JPY','GEP Normalized Spend (JPY)','float')
,('GEP_NORM_SPEND_CHF','GEP Normalized Spend (CHF)','float')
,('GEP_NORM_SPEND_MXN','GEP Normalized Spend (MXN)','float')
,('GEP_NORM_SPEND_NOK','GEP Normalized Spend (NOK)','float')
,('GEP_NORMALIZED_PO_UNIT_PRICE_USD','GEP Normalized PO Unit Price (USD)','float')
,('GEP_NORMALIZED_PO_UNIT_PRICE_EUR','GEP Normalized PO Unit Price (EUR)','float')
,('GEP_NORM_DATE','GEP Normalized Date','date')
,('CREATED_DATE','Record Entry Date','datetime')
,('MODIFIED_DATE','Record Modifed Date','datetime')
,('GEP_SUPP_CLUSTER','GEP Vendor Normalization Cluster ID','int')
,('GEP_CLN_CLUSTER','GEP Classification Cluster ID','bigint')
,('GEP_BU_CLUSTER','GEP BU Cluster ID','int')
,('GEP_EXCLUDE','GEP Exclude','boolean')
,('GEP_EXCLUSION_COMMENTS','GEP Exclusion Comments','nvarchar')
,('GEP_EXCLUSION_CRITERIA','GEP Exclusion Criteria','nvarchar')
,('GEP_TRANSLATED_SUPP_NAME','GEP Translated Supplier Name','nvarchar')
,('GEP_TRANSLATED_INVOICE_LINE_DESCRIPTION','GEP Translated Invoice Description','nvarchar')
,('GEP_TRANSLATED_PO_DESCRIPTION','GEP Translated PO Description','nvarchar')
,('GEP_TRANSLATED_MATERIAL_DESCRIPTION','GEP Translated Material Description','nvarchar')
,('GEP_TRANSLATED_DESCRIPTION_2','GEP Translated Description 2','nvarchar')
,('GEP_ACTUAL_PAYMENT_TERM_DAYS','GEP Actual Payment Term Days','float')
,('GEP_PO_AVG_UNIT_PRICE','GEP PO Average Unit Price','float')
,('GEP_ONE_TIME_SUPP_FLAG','GEP One Time Vendor Flag','nvarchar')
,('GEP_ONE_ITEM_MULTI_SUPP_FLAG','GEP One Item Multiple Supplier Flag','nvarchar')
,('GEP_ONE_SUPP_MULTI_BU_FLAG','GEP One Supplier Multiple BU Flag','nvarchar')
,('GEP_ONE_SUPP_MULTI_PAYTERM_FLAG','GEP One Supplier Multiple Payment Term Flag','nvarchar')
,('GEP_SUPP_SPEND_TOP_BUCKET','GEP Supplier Spend Top Bucket','nvarchar')
,('GEP_SUPP_SPEND_BUCKET','GEP Supplier Spend Bucket','nvarchar')
,('GEP_INV_SPEND_BUCKET','GEP Invoice Spend Bucket','nvarchar')
,('GEP_PO_SPEND_BUCKET','GEP PO Spend Bucket','nvarchar')
,('GEP_PAYTERM_BUCKET','GEP Invoice Payment Term Days Bucket','nvarchar')
,('GEP_TRANS_BUCKET','GEP Transaction Spend Bucket','nvarchar')
,('GEP_PRIORITY','GEP CF Priority Bucket','nvarchar')
,('GEP_QA_FLAG_VNE','GEP VNE QA Flag','nvarchar')
,('GEP_QA_FLAG_CF','GEP CF QA Flag','nvarchar')
,('GEP_QA_FLAG_OTH','GEP QA Flag Other','nvarchar')
,('GEP_SLA_FLAG_VNE','GEP VNE SLA Flag','nvarchar')
,('GEP_SLA_FLAG_CF','GEP CF SLA Flag','nvarchar')
,('GEP_AI_SOURCE_CF','GEP Classification Source','nvarchar')
,('GEP_AI_ALGO_VNE','GEP VNE AI Algorithm','nvarchar')
,('GEP_AI_ALGO_CF','GEP CF AI Algorithm','nvarchar')
,('GEP_FEEDBACK_FLAG','GEP CF Feedback Flag','nvarchar')
,('GEP_VNE_FEEDBACK_FLAG','GEP VNE Feedback Flag','nvarchar')
,('GEP_VNE_SOURCE','GEP Supplier Normalization Method L1','nvarchar')
,('GEP_VNE_SOURCE_2','GEP Supplier Normalization Method L2','nvarchar')
,('GEP_VNE_HISTORICAL_FLAG','GEP Supplier Normalization Historical Flag','nvarchar')
,('GEP_UP_STATUS_FLAG','GEP Parent Linkage Status Flag','nvarchar')
,('GEP_UP_SOURCE','GEP Parent Linkage Method L1','nvarchar')
,('GEP_UP_SOURCE_2','GEP Parent Linkage Method L2','nvarchar')
,('GEP_UP_HISTORICAL_FLAG','GEP Parent Linkage Historical Flag','nvarchar')
,('GEP_CF_SOURCE','GEP Classification Method L1','nvarchar')
,('GEP_CF_SOURCE_2','GEP Classification Method L2','nvarchar')
,('GEP_CF_HISTORICAL_FLAG','GEP Classification Historical Flag','nvarchar')
,('GEP_JOB_ID','GEP Job ID','bigint')
,('GEP_JOB_NAME','GEP Job Name','nvarchar')
,('GEP_COMMENTS','GEP Comments','nvarchar')
,('GEP_DUPLICATE_KEY_FLAG','GEP Duplicate (Key) Flag','nvarchar')
,('GEP_DUPLICATE_KEY_ID','GEP Duplicate (key) ID','nvarchar')
,('GEP_DUPLICATE_ALL_FLAG','GEP Duplicate (All) Flag','nvarchar')
,('GEP_DUPLICATE_ALL_ID','GEP Duplicate (All) ID','nvarchar')
,('GEP_RULE_ID','GEP Rule ID (Classification)','int')
,('GEP_RULE_ID_VNE','GEP Rule ID (Vendor Normalization)','nvarchar')
,('GEP_RULE_ID_OTHER','GEP Rule ID (Other)','int')
,('RULE_PROVIDER','GEP Rule Provider (Classification)','nvarchar')
,('RULE_SOURCE','GEP Rule Source (Classification)','nvarchar')
,('RULE_TYPE_NAME','GEP Rule Type','nvarchar')
,('GEP_CF_STATUS_FLAG','GEP Classification Status Flag','nvarchar')
,('GEP_VNE_STATUS_FLAG','GEP Supplier Normalization Status Flag','nvarchar')
,('GEP_CONFIDENCE_FLAG','GEP Confidence Flag','nvarchar')
,('GEP_DELIVERY_STATUS','GEP Delivery Status Flag','nvarchar')
,('GEP_CF_USER','GEP CF User','nvarchar')
,('GEP_VNE_USER','GEP VNE User','nvarchar')
,('GEP_AI_DL_CATEGORY_L1','GEP AI DL Category L1','nvarchar')
,('GEP_AI_DL_CATEGORY_L2','GEP AI DL Category L2','nvarchar')
,('GEP_AI_DL_CATEGORY_L3','GEP AI DL Category L3','nvarchar')
,('GEP_AI_DL_CATEGORY_L4','GEP AI DL Category L4','nvarchar')
,('GEP_AI_DL_SUPPLIER_SIC_NAICS','GEP AI DL Supplier SIC NAICS','nvarchar')
,('GEP_MANAGED_CATEGORY_FLAG','GEP Managed Category','nvarchar')
,('GEP_SOURCING_SCOPE_FLAG','GEP Sourcing Scope','nvarchar')
,('GEP_SOLE_SOURCING_FLAG','GEP Sole Sourcing','nvarchar')
,('GEP_BUYING_CHANNEL','GEP Buying Channel','nvarchar')
,('GEP_PAYMENT_CHANNEL','GEP Payment Channel','nvarchar')
,('GEP_SOURCING_REGION','GEP Sourcing Region','nvarchar')
,('GEP_PO_NON_PO_FLAG','GEP PO Flag','nvarchar')
,('GEP_CONTRACT_FLAG','GEP Contract Flag','nvarchar')
,('GEP_CONFIDENTIAL_FLAG','GEP Confidential Flag','nvarchar')
,('GEP_INTERCOMPANY_FLAG','GEP Intercompany Flag','nvarchar')
,('GEP_DISCONTINUED_FLAG','GEP Discontinued Flag','nvarchar')
,('GEP_CATEGORY_MANAGER_GLOBAL','GEP Category Manager Global','nvarchar')
,('GEP_CATEGORY_MANAGER_REGION','GEP Category Manager Region','nvarchar')
,('INVOICE_UNIT_PRICE_IN_LOCAL_CURRENCY','Invoice Unit Price Local','float')
,('BUSINESS_DIVISION','Business Division','nvarchar')
,('DEPARTMENT_CODE','Department Code','nvarchar')
,('DEPARTMENT_DESCRIPTION','Department Description','nvarchar')
,('BUSINESS_UNIT_CODE','Business Unit Code','nvarchar')
,('BUSINESS_UNIT_DESC','Business Unit','nvarchar')
,('BUSINESS_GROUP_DESC','BU Group','nvarchar')
,('BUSINESS_GROUP_DESC_2','BU Group 2','nvarchar')
,('BUSINESS_GROUP_DESC_3','BU Group 3','nvarchar')
,('BUSINESS_GROUP_DESC_4','BU Group 4','nvarchar')
,('BUSINESS_GROUP_DESC_5','BU Group 5','nvarchar')
,('BUSINESS_GROUP_DESC_6','BU Group 6','nvarchar')
,('GEP_NORM_BUSINESS_UNIT','GEP Normalized Business Unit','nvarchar')
,('GEP_NORM_BU_LEVEL1','GEP Normalized Business Group Level 1','nvarchar')
,('GEP_NORM_BU_LEVEL2','GEP Normalized Business Group Level 2','nvarchar')
,('GEP_NORM_BU_LEVEL3','GEP Normalized Business Group Level 3','nvarchar')
,('GEP_NORM_BU_LEVEL4','GEP Normalized Business Group Level 4','nvarchar')
,('COMPANY_CODE','Company Code','nvarchar')
,('COMPANY_NAME','Company Name','nvarchar')
,('COMPANY_COUNTRY','Company Country','nvarchar')
,('COMPANY_REGION','Company Region','nvarchar')
,('GEP_NORM_COMPANY','GEP Normalized Company','nvarchar')
,('GEP_NORM_COMPANY_COUNTRY','GEP Business Country','nvarchar')
,('GEP_NORM_COMPANY_SUB_REGION','GEP Business Sub Region','nvarchar')
,('GEP_NORM_COMPANY_REGION','GEP Business Region','nvarchar')
,('PLANT_TYPE','Facility Type','nvarchar')
,('PLANT_CODE','Facility Code','nvarchar')
,('PLANT_NAME','Facility Name','nvarchar')
,('PLANT_ADDRESS','Facility Address','nvarchar')
,('PLANT_CITY','Facility City','nvarchar')
,('PLANT_STATE','Facility State','nvarchar')
,('PLANT_ZIP_CODE','Facility Zip','nvarchar')
,('PLANT_COUNTRY','Facility Country','nvarchar')
,('PLANT_REGION','Facility Region','nvarchar')
,('GEP_NORM_PLANT_NAME','GEP Normalized Facility','nvarchar')
,('SUPPLIER_NUMBER','Invoice Supplier Number','nvarchar')
,('SUPPLIER_NAME','Invoice Supplier Name','nvarchar')
,('SUPPLIER_ADDRESS','Invoice Supplier Address','nvarchar')
,('SUPPLIER_CITY','Invoice Supplier City','nvarchar')
,('SUPPLIER_ZIP_CODE','Invoice Supplier Zip Postal Code','nvarchar')
,('SUPPLIER_STATE','Invoice Supplier State','nvarchar')
,('SUPPLIER_COUNTRY','Invoice Supplier Country','nvarchar')
,('SUPPLIER_PAYTERM_CODE','Supplier Payment Term Code','nvarchar')
,('SUPPLIER_PAYTERM_DESC','Supplier Payment Term Desc','nvarchar')
,('SUPPLIER_TYPE','Supplier Type','nvarchar')
,('SUPPLIER_DIVERSITY_CODE','Supplier Diversity Code','nvarchar')
,('SUPPLIER_DUNS_NUMBER','Supplier DUNS Number','nvarchar')
,('SUPPLIER_ORIGIN_COUNTRY','Supplier Country of Origin','nvarchar')
,('SUPPLIER_DUNS_SSI','Supplier DUNS SSI','nvarchar')
,('SUPPLIER_DUNS_SER','Supplier DUNS SER','nvarchar')
,('SUPPLIER_DUNS_PAYDEX','Supplier DUNS PAYDEX','nvarchar')
,('SUPPLIER_DUNS_GLOBAL_ULTIMATE_COMPANY_NAME','Supplier DUNS Global Ultimate Company','nvarchar')
,('SUPPLIER_DUNS_GLOBAL_ULTIMATE_COUNTRY','Supplier DUNS Global Ultimate Country','nvarchar')
,('SUPPLIER_PREFERRED_STATUS','Supplier Preferred status','nvarchar')
,('CUSTOMER_SUPPLIER_STATUS','Customer Supplier Status','nvarchar')
,('GEP_DELTAFLAG','GEP CF Delta Flag','nvarchar')
,('GEP_ENRICHFLAG','GEP VNE Enrich Flag','nvarchar')
,('GEP_NEW_VENDOR_FLAG','GEP New Vendor Flag','nvarchar')
,('GEP_NORM_SUPP_NUMBER','GEP Supplier Number','nvarchar')
,('GEP_NORM_SUPP_NAME','GEP Normalized Supplier','nvarchar')
,('GEP_ULT_PARENT','GEP Ultimate Parent','nvarchar')
,('GEP_NORM_SUPP_CITY','GEP Supplier City','nvarchar')
,('GEP_NORM_SUPP_STATE','GEP Supplier State','nvarchar')
,('GEP_NORM_SUPP_COUNTRY','GEP Supplier Country','nvarchar')
,('GEP_NORM_SUPP_SUB_REGION','GEP Supplier Sub Region','nvarchar')
,('GEP_NORM_SUPP_REGION','GEP Supplier Region','nvarchar')
,('GEP_PREFERRED_SUPPLIER_STATUS','GEP Preferred Supplier','nvarchar')
,('GEP_CUSTOMER_SUPPLIER_STATUS','GEP Customer Supplier Flag','nvarchar')
,('GEP_AI_SUPPLIER_LOB','GEP AI DL Supplier LOB','nvarchar')
,('GEP_SUPPLIER_PAYMENT_TERM','GEP Normalized Supplier Payment Term','nvarchar')
,('GEP_SUPPLIER_NET_DAYS','GEP Supplier Payment Term Net Days','float')
,('GEP_SUPPLIER_DISCOUNT_PERCENTAGE','GEP Supplier Payment Term Discount Percentage','float')
,('GEP_SUPPLIER_DISCOUNT_DAYS','GEP Supplier Payment Term Net Days Discount Adjusted','float')
,('PAYMENT_TERM_CODE','Invoice Payment Term Code','nvarchar')
,('PAYMENT_TERM_DESCRIPTION','Invoice Payment Term Desc','nvarchar')
,('GEP_NORM_PAYMENT_TERM','GEP Normalized Invoice Payment Term','nvarchar')
,('GEP_NORM_NET_DAYS','GEP Invoice Payment Term Net Days','float')
,('GEP_NORM_DISCOUNT_PERCENTAGE','GEP Invoice Payment Term Discount Percentage','float')
,('GEP_NORM_DISCOUNT_DAYS','GEP Invoice Payment Term Net Days Discount Adjusted','float')
,('GL_ACCOUNT_CODE','GL Account Code','nvarchar')
,('GL_ACCOUNT_NAME','GL Account Name','nvarchar')
,('GL_ACCOUNT_HIERARCHY_L1','GL Hierarchy 1','nvarchar')
,('GL_ACCOUNT_HIERARCHY_L2','GL Hierarchy 2','nvarchar')
,('CHART_OF_ACCOUNT_CODE','Chart of Account Code','nvarchar')
,('CHART_OF_ACCOUNT_NAME','Chart of Account Name','nvarchar')
,('COST_CENTER_CODE','Cost Center Code','nvarchar')
,('COST_CENTER_DESCRIPTION','Cost Center Name','nvarchar')
,('COST_CENTER_HIERARCHY_L1','Cost Center Hierarchy 1','nvarchar')
,('COST_CENTER_HIERARCHY_L2','Cost Center Hierarchy 2','nvarchar')
,('COST_CENTER_HIERARCHY_L3','Cost Center Hierarchy 3','nvarchar')
,('COST_CENTER_HIERARCHY_L4','Cost Center Hierarchy 4','nvarchar')
,('COST_CENTER_HIERARCHY_L5','Cost Center Hierarchy 5','nvarchar')
,('CONTRACT_SOURCE_SYSTEM','Contract Source System','nvarchar')
,('CONTRACT_NUMBER','Contract Number','nvarchar')
,('CONTRACT_LINE_NUMBER','Contract Line Number','nvarchar')
,('CONTRACT_AMOUNT','Contract Amount','float')
,('CONTRACT_START_DATE','Contract Start Date','date')
,('CONTRACT_END_DATE','Contract End Date','date')
,('CONTRACT_SUPPLIER_NUMBER','Contract Supplier Number','nvarchar')
,('CONTRACT_SUPPLIER_NAME','Contract Supplier Name','nvarchar')
,('CONTRACT_DESCRIPTION','Contract Description','nvarchar')
,('CONTRACT_DESCRIPTION_2','Contract Description 2','nvarchar')
,('CONTRACT_CATEGORY_CODE','Contract Category Code','nvarchar')
,('CONTRACT_CATEGORY_1','Contract Category 1','nvarchar')
,('CONTRACT_CATEGORY_2','Contract Category 2','nvarchar')
,('CONTRACT_CATEGORY_3','Contract Category 3','nvarchar')
,('CONTRACT_CATEGORY_4','Contract Category 4','nvarchar')
,('CONTRACT_OWNER','Contract Owner','nvarchar')
,('CONTRACT_STATUS','Contract Status','nvarchar')
,('CONTRACT_TYPE','Contract Type','nvarchar')
,('CONTRACT_BUSINESS_UNIT','Contract Business Unit','nvarchar')
,('CONTRACT_COMPANY','Contract Company','nvarchar')
,('CONTRACT_BU_COUNTRY','Contract BU Country','nvarchar')
,('CONTRACT_BU_REGION','Contract BU Region','nvarchar')
,('CONTRACT_RENEWAL_TYPE','Contract Renewal Type','nvarchar')
,('CLIENT_CHILD_SUPPLIER','Client Child Supplier','nvarchar')
,('CLIENT_PARENT_SUPPLIER','Client Parent Supplier','nvarchar')
,('CLIENT_CATEGORY_CODE','Client Category Code','nvarchar')
,('CLIENT_CATEGORY_1','Client Category 1','nvarchar')
,('CLIENT_CATEGORY_2','Client Category 2','nvarchar')
,('CLIENT_CATEGORY_3','Client Category 3','nvarchar')
,('CLIENT_CATEGORY_4','Client Category 4','nvarchar')
,('GEP_CATEGORY_KEY','GEP Category Key','nvarchar')
,('GEP_CATEGORY_CODE','GEP Category Code','nvarchar')
,('GEP_CATEGORY_LEVEL_1','GEP Category Level 1','nvarchar')
,('GEP_CATEGORY_LEVEL_2','GEP Category Level 2','nvarchar')
,('GEP_CATEGORY_LEVEL_3','GEP Category Level 3','nvarchar')
,('GEP_CATEGORY_LEVEL_4','GEP Category Level 4','nvarchar')
,('GEP_CATEGORY_LEVEL_5','GEP Category Level 5','nvarchar')
,('GEP_CATEGORY_LEVEL_6','GEP Category Level 6','nvarchar')
,('GEP_CATEGORY_LEVEL_7','GEP Category Level 7','nvarchar')
,('GEP_CATEGORY_VERSION','GEP Category Version','nvarchar')
,('GEP_PRODUCT_SERVICE_FLAG','GEP Product Service Flag','nvarchar')
,('GEP_DIRECT_INDIRECT_FLAG','GEP Direct Indirect Flag','nvarchar')
,('GEP_SOURCING_CATEGORY','GEP Sourcing Category','nvarchar')
,('GEP_MRO_CAPITAL_FLAG','GEP MRO Capital Flag','nvarchar')
,('GEP_UNSPSC_KEY','GEP UNSPSC Key','nvarchar')
,('GEP_UNSPSC_CODE','GEP UNSPSC Code','nvarchar')
,('GEP_UNSPSC_L1_SEGMENT','GEP UNSPSC L1 Segment','nvarchar')
,('GEP_UNSPSC_L2_FAMILY','GEP UNSPSC L2 Family','nvarchar')
,('GEP_UNSPSC_L3_CATEGORY','GEP UNSPSC L3 Category','nvarchar')
,('GEP_UNSPSC_L4_COMMODITY','GEP UNSPSC L4 Commodity','nvarchar')
,('GEP_UNSPSC_VERSION','GEP UNSPSC Version','nvarchar')
,('GEP_UNSPSC_STATUS','GEP UNSPSC Status','nvarchar')
,('PO_SOURCE_SYSTEM','PO Source System','nvarchar')
,('PO_STATUS','PO Status','nvarchar')
,('PO_TYPE','PO Type','nvarchar')
,('PO_DOCUMENT_TYPE','PO Document Type','nvarchar')
,('PO_NUMBER','PO Number','nvarchar')
,('PO_LINE_NUMBER','PO Line Number','nvarchar')
,('PO_EXTRA_PO_KEY','PO Number 2','nvarchar')
,('PO_EXTRA_PO_LINE_KEY','PO Number 3','nvarchar')
,('PO_DOCUMENT_DATE','PO Date','date')
,('PO_COMPANY_CODE','PO Company Code','nvarchar')
,('PO_COMPANY_NAME','PO Company Name','nvarchar')
,('PO_LINE_AMOUNT_NORMALIZED','PO Line Amount Normalized','float')
,('GEP_CATEGORY_MANAGER_LOCAL','GEP Category Manager Local','nvarchar')
,('PO_LINE_AMOUNT_CURRENCY','PO Line Amount Currency','nvarchar')
,('PO_OPEN_LINE_AMOUNT_NORMALIZED','PO Open Line Amount Normalized','float')
,('PO_LINE_AMOUNT_LOCAL','PO Line Amount Local','float')
,('PO_OPEN_LINE_AMOUNT_CURRENCY','PO Open Line Amount Currency','nvarchar')
,('PO_UNIT_PRICE_NORMALIZED','PO Unit Price Normalized','float')
,('PO_OPEN_LINE_AMOUNT_LOCAL','PO Open Line Amount Local','float')
,('PO_UNIT_PRICE_CURRENCY','PO Unit Price Currency','nvarchar')
,('PO_PAYMENT_TERM','PO Payment Term','nvarchar')
,('GEP_NORM_PO_PAYMENT_TERM','GEP Normalized PO Payment Term','nvarchar')
,('PO_QUANTITY','PO Quantity','float')
,('PO_QUANTITY_NORMALIZED','GEP Normalized PO Quanity','float')
,('PO_UOM','PO UOM','nvarchar')
,('PO_UOM_NORMALIZED','GEP Normalized PO UOM','nvarchar')
,('PO_DESCRIPTION_1','PO Description','nvarchar')
,('PO_DESCRIPTION_2','PO Description 2','nvarchar')
,('PO_PLANT_CODE','PO Plant Code','nvarchar')
,('PO_PLANT_NAME','PO Plant Name','nvarchar')
,('PO_PLANT_ADDRESS','PO Plant Address','nvarchar')
,('PO_PLANT_CITY','PO Plant City','nvarchar')
,('PO_PLANT_STATE','PO Plant State','nvarchar')
,('PO_PLANT_ZIP','PO Plant Zip','nvarchar')
,('PO_PLANT_COUNTRY','PO Plant Country','nvarchar')
,('PO_PLANT_REGION','PO Plant Region','nvarchar')
,('PO_PLANT_TYPE','PO Plant Type','nvarchar')
,('PO_CATALOG_STATUS','PO Catalog','nvarchar')
,('PO_SUPPLIER_NUMBER','PO Supplier Number','nvarchar')
,('PO_SUPPLIER_NAME','PO Supplier Name','nvarchar')
,('PO_BUYER_CODE','PO Buyer Code','nvarchar')
,('PO_BUYER_NAME','PO Buyer Name','nvarchar')
,('PO_PURCHASING_GROUP_CODE','PO Purchasing Group Code','nvarchar')
,('PO_PURCHASING_GROUP_NAME','PO Purchasing Group Name','nvarchar')
,('PO_PURCHASING_GROUP_NAME_2','PO Purchasing Group Name 2','nvarchar')
,('PO_PURCHASING_ORG_CODE','PO Purchasing Org Code','nvarchar')
,('PO_PURCHASING_ORG_NAME','PO Purchasing Org Name','nvarchar')
,('PO_CREATED_BY','PO Created By','nvarchar')
,('PO_APPROVER','PO Approver','nvarchar')
,('PO_GL_CODE','PO GL Code','nvarchar')
,('PO_GL_NAME','PO GL Name','nvarchar')
,('PO_COST_CENTER_CODE','PO Cost Center Code','nvarchar')
,('PO_COST_CENTER_NAME','PO Cost Center Name','nvarchar')
,('PO_LANGUAGE','PO Language','nvarchar')
,('PO_CATEGORY_CODE','PO Category Code','nvarchar')
,('PO_CATEGORY_1','PO Category 1','nvarchar')
,('PO_CATEGORY_2','PO Category 2','nvarchar')
,('PO_CATEGORY_3','PO Category 3','nvarchar')
,('PO_CATEGORY_4','PO Category 4','nvarchar')
,('ITEM_MATERIAL_NUMBER','Material Number','nvarchar')
,('ITEM_MATERIAL_REVISION_NUMBER','Maerial Revision Number','nvarchar')
,('ITEM_MATERIAL_DESCRIPTION','Material Description','nvarchar')
,('ITEM_MATERIAL_GROUP_CODE','Material Group Code','nvarchar')
,('ITEM_MATERIAL_GROUP_DESCRIPTION','Material Group Description','nvarchar')
,('ITEM_MATERIAL_TYPE','Material Type','nvarchar')
,('ITEM_MANUFACTURER_NAME','Manufacturer Name','nvarchar')
,('ITEM_MANUFACTURER_PART_NUMBER','Manufacturer Part No','nvarchar')
,('ITEM_SUPPLIER_PART_NUMBER','Supplier Part No','nvarchar')
,('ITEM_MATERIAL_CATEGORY_CODE','Material Category Code','nvarchar')
,('ITEM_MATERIAL_CATEGORY_1','Material Category L1','nvarchar')
,('ITEM_MATERIAL_CATEGORY_2','Material Category L2','nvarchar')
,('ITEM_MATERIAL_CATEGORY_3','Material Category L3','nvarchar')
,('ITEM_MATERIAL_CATEGORY_4','Material Category L4','nvarchar')
,('ITEM_MATERIAL_NAME','Material Name','nvarchar')
,('ITEM_MATERIAL_STOCK_INDICATOR','Material Stock Indicator','nvarchar')
,('ITEM_MATERIAL_CRITICALITY','Material Criticality','nvarchar')
,('ITEM_MATERIAL_LEAD_TIME','Material Lead Time','float')
,('ITEM_MATERIAL_STANDARD_COST','Material Standard Cost','float')
,('ITEM_MATERIAL_STANDARD_COST_CURRENCY','Material Standard Cost Currency','nvarchar')
,('ITEM_MATERIAL_STANDARD_UOM','Material Standard UOM','nvarchar')
,('ITEM_MATERIAL_STANDARD_COST_DATE','Material Standard Cost Date','date')
,('ITEM_MATERIAL_BOM_EQUIPMENT','Material BOM Equipment','nvarchar')
,('ITEM_MATERIAL_ORIGIN_COUNTRY','Material Origin Country','nvarchar')
,('SOURCESYSTEM_1','Source System 1','nvarchar')
,('SOURCESYSTEM_2','Source System 2','nvarchar')
,('SOURCESYSTEM_3','Source System 3','nvarchar')
,('GEP_NORM_SOURCESYSTEM_1','GEP Source System','nvarchar')
,('GEP_NORM_SOURCESYSTEM_2','GEP Source System Level 2','nvarchar')
,('GEP_NORM_SOURCESYSTEM_3','GEP Source System Level 3','nvarchar')
,('PROFIT_CENTER_CODE','Profit Center Code','nvarchar')
,('PROFIT_CENTER_NAME','Profit Center Name','nvarchar')
,('PROFIT_CENTER_HIERARCHY_1','Profit Center Hierarchy 1','nvarchar')
,('PROFIT_CENTER_HIERARCHY_2','Profit Center Hierarchy 2','nvarchar')
,('PROFIT_CENTER_HIERARCHY_3','Profit Center Hierarchy 3','nvarchar')
,('PROFIT_CENTER_HIERARCHY_4','Profit Center Hierarchy 4','nvarchar')
,('PROFIT_CENTER_HIERARCHY_5','Profit Center Hierarchy 5','nvarchar')
,('PROFIT_CENTER_HIERARCHY_6','Profit Center Hierarchy 6','nvarchar')
,('INCOTERMS_CODE','Inco Terms Code','nvarchar')
,('INCOTERMS_DESCRIPTION','Inco Terms Description','nvarchar')
,('GEP_DIVERSITY_FLAG','GEP Diversity Flag','nvarchar')
,('GEP_DIVERSITY_TYPE','Gep Diversity Type','nvarchar')
,('GEP_DIVERSITY_8A_CERTIFICATION_INDICATOR','GEP Diversity 8a Certification Indicator','nvarchar')
,('GEP_DIVERSITY_AIRPORT_CONCESSION_DISADVANTAGED_BUSINESS_ENTERPRISE_INDICATOR','GEP Diversity Airport Concession Disadvantaged Business Enterprise Indicator','nvarchar')
,('GEP_DIVERSITY_ALASKAN_NATIVE_CORPORATION_INDICATOR','GEP Diversity Alaskan Native Corporation Indicator','nvarchar')
,('GEP_DIVERSITY_CERTIFIED_SMALL_BUSINESS_INDICATOR','GEP Diversity Certified Small Business Indicator','nvarchar')
,('GEP_DIVERSITY_DISABLED_VETERAN_BUSINESS_ENTERPRISE_INDICATOR','GEP Diversity Disabled Veteran Business Enterprise Indicator','nvarchar')
,('GEP_DIVERSITY_DISABLED_OWNED_BUSINESS_INDICATOR','GEP Diversity Disabled Owned Business Indicator','nvarchar')
,('GEP_DIVERSITY_DISADVANTAGED_BUSINESS_ENTERPRISE_INDICATOR','GEP Diversity Disadvantaged Business Enterprise Indicator','nvarchar')
,('GEP_DIVERSITY_DISADVANTAGED_VETERAN_ENTERPRISE_INDICATOR','GEP Diversity Disadvantaged Veteran Enterprise Indicator','nvarchar')
,('GEP_DIVERSITY_HUB_ZONE_CERTIFIED_BUSINESS_INDICATOR','GEP Diversity Hub Zone Certified Business Indicator','nvarchar')
,('GEP_DIVERSITY_LABOR_SURPLUS_AREA_INDICATOR','GEP Diversity Labor Surplus Area Indicator','nvarchar')
,('GEP_DIVERSITY_MINORITY_BUSINESS_ENTERPRISE_INDICATOR','GEP Diversity Minority Business Enterprise Indicator','nvarchar')
,('GEP_DIVERSITY_MINORITY_COLLEGE_INDICATOR','GEP Diversity Minority College Indicator','nvarchar')
,('GEP_DIVERSITY_MINORITY_OWNED_INDICATOR','GEP Diversity Minority Owned Indicator','nvarchar')
,('GEP_DIVERSITY_OUT_OF_BUSINESS_INDICATOR','GEP Diversity Out Of Business Indicator','nvarchar')
,('GEP_DIVERSITY_POLITICAL_DISTRICT','GEP Diversity Political District','nvarchar')
,('GEP_DIVERSITY_SERVICE_DISABLED_VETERAN_OWNED_INDICATOR','GEP Diversity Service Disabled Veteran Owned Indicator','nvarchar')
,('GEP_DIVERSITY_SMALL_BUSINESS_INDICATOR','GEP Diversity Small Business Indicator','nvarchar')
,('GEP_DIVERSITY_SMALL_DISADVANTAGED_BUSINESS_INDICATOR','GEP Diversity Small Disadvantaged Business Indicator','nvarchar')
,('GEP_DIVERSITY_VETERAN_BUSINESS_ENTERPRISE_INDICATOR','GEP Diversity Veteran Business Enterprise Indicator','nvarchar')
,('GEP_DIVERSITY_VETERAN_OWNED_INDICATOR','GEP Diversity Veteran Owned Indicator','nvarchar')
,('GEP_DIVERSITY_VIETNAM_VETERAN_OWNED_INDICATOR','GEP Diversity Vietnam Veteran Owned Indicator','nvarchar')
,('GEP_DIVERSITY_OTHER_VETERAN_OWNED_INDICATOR','GEP Diversity Other Veteran Owned Indicator','nvarchar')
,('GEP_DIVERSITY_WOMAN_OWNED_BUSINESS_ENTERPRISE_INDICATOR','GEP Diversity Woman Owned Business Enterprise Indicator','nvarchar')
,('GEP_DIVERSITY_WOMAN_OWNED_INDICATOR','GEP Diversity Woman Owned Indicator','nvarchar')
,('GEP_DIVERSITY_AFRICAN_AMERICAN_OWNED_INDICATOR','GEP Diversity African American Owned Indicator','nvarchar')
,('GEP_DIVERSITY_ASIAN_PACIFIC_AMERICAN_OWNED_INDICATOR','GEP Diversity Asian Pacific American Owned Indicator','nvarchar')
,('GEP_DIVERSITY_HISPANIC_AMERICAN_OWNED_INDICATOR','GEP Diversity Hispanic American Owned Indicator','nvarchar')
,('GEP_DIVERSITY_NATIVE_AMERICAN_OWNED_INDICATOR','GEP Diversity Native American Owned Indicator','nvarchar')
,('GEP_DIVERSITY_SUBCONTINENT_ASIAN_AMERICAN_OWNED_INDICATOR','GEP Diversity Subcontinent Asian American Owned Indicator','nvarchar')
,('GEP_OTHER_DIVERSITY','Gep Diversity Other','nvarchar')
,('SOURCEFILENAME','Source File Name','nvarchar')
,('GEP_YEAR','GEP Calendar Year','int')
,('GEP_QTR','GEP Calendar Quarter','nvarchar')
,('GEP_MONTH','GEP Calendar Month','nvarchar')
,('GEP_FISCAL_ID','GEP Fiscal Period ID','nvarchar')
,('GEP_FISCAL_YEAR','GEP Fiscal Year','nvarchar')
,('GEP_FISCAL_QTR','GEP Fiscal Quarter','nvarchar')
,('GEP_FISCAL_MONTH','GEP Fiscal Month','nvarchar')
,('CARD_HOLDER_ID','Card holder ID','nvarchar')
,('CARD_HOLDER_NAME','Card holder Name','nvarchar')
,('MERCHANT_CATEGORY_CODE','Merchant Category Code','nvarchar')
,('MERCHANT_CATEGORY_CODE_TITLE','Merchant Category Code Title','nvarchar')
,('MERCHANT_CATEGORY_GROUP_CODE','Merchant Category Group Code','nvarchar')
,('MERCHANT_CATEGORY_GROUP_TITLE','Merchant Category Group Title','nvarchar')
,('EXPENSE_TYPE','Expense Type','nvarchar')
,('SIC_CODE','SIC Code','nvarchar')
,('SIC_TITLE','SIC Title','nvarchar')
,('NAICS_CODE','NAICS Code','nvarchar')
,('NAICS_TITLE','NAICS Title','nvarchar')
,('PROJECT_CODE','Project Code','nvarchar')
,('PROJECT_NAME','Project Name','nvarchar')
,('PROJECT_DESC','Project Description','nvarchar')
,('WORK_ORDER_NUMBER','Work Order Number','nvarchar')
,('WORK_ORDER_DESC','Work Order Description','nvarchar')
,('WBS_CODE','WBS Code','nvarchar')
,('WBS_DESC','WBS Description','nvarchar')
,('PRODUCT','Product','nvarchar')
,('PRODUCT_CATEGORY','Product Category','nvarchar')
,('GEP_CONSOLIDATION_DESCRIPTION','GEP Consolidated Description','nvarchar')
,('REQUISITION_SOURCE_SYSTEM','Requisition Source System','nvarchar')
,('REQUISITION_NUMBER','Requisition Number','nvarchar')
,('REQUISITION_LINE_NUMBER','Requisition Line Number','nvarchar')
,('REQUISITION_SUPPLIER_NUMBER','Requisition Supplier Number','nvarchar')
,('REQUISITION_SUPPLIER_NAME','Requisition Supplier Name','nvarchar')
,('REQUISITION_CREATION_DATE','Requisition Creation Date','date')
,('REQUISITION_APPROVED_DATE','Requisition Approved Date','date')
,('REQUISITION_OWNER','Requisition Owner','nvarchar')
,('REQUISITION_AMOUNT','Requisition Amount','float')
,('REQUISITION_LINE_DESCRIPTION','Requisition Line Description','nvarchar')
,('GR_SOURCE_SYSTEM','Goods Receipt Source System','nvarchar')
,('GR_NUMBER','Goods Receipt Number','nvarchar')
,('GR_LINE_NUMBER','Goods Receipt Line Number','nvarchar')
,('GR_SUPPLIER_NUMBER','Goods Receipt Supplier Number','nvarchar')
,('GR_SUPPLIER_NAME','Goods Receipt Supplier Name','nvarchar')
,('GR_DATE','Goods Receipt Date','date')
,('GR_LINE_AMOUNT','Goods Receipt Line Amount','float')
,('GR_UNIT_PRICE','Goods Receipt Unit Price','float')
,('GR_QUANTITY','Goods Receipt Quantity','float')
,('GR_UOM','Goods Receipt UoM','nvarchar')
,('IMPORTEXPORTUID1','Import Export UID 1','bigint')
,('IMPORTEXPORTUID2','Import Export UID 2','bigint')
,('IMPORTEXPORTUID3','Import Export UID 3','bigint')
,('IMPORTEXPORTUID4','Import Export UID 4','bigint')
,('IMPORTEXPORTUID5','Import Export UID 5','bigint')
,('IMPORTEXPORTUID6','Import Export UID 6','bigint')
,('IMPORTEXPORTUID7','Import Export UID 7','bigint')
,('IMPORTEXPORTUID8','Import Export UID 8','bigint')
,('IMPORTEXPORTUID9','Import Export UID 9','bigint')
,('IMPORTEXPORTUID10','Import Export UID 10','bigint')
,('GEP_AI_SOURCE_VNE','GEP Supplier Normalization Source','nvarchar')
,('GEP_AI_SOURCE_UP','GEP Parent Linkage Source','nvarchar')
,('GEP_AI_DL_CATEGORY_L5','GEP AI DL Category L5','nvarchar')
,('GEP_AI_DL_CATEGORY_L6','GEP AI DL Category L6','nvarchar')
,('GEP_AI_DL_CATEGORY_L7','GEP AI DL Category L7','nvarchar')
,('GEP_NORM_SPEND_AED','GEP Normalized Spend (AED)','float')
,('GEP_NORM_SPEND_INR','GEP Normalized Spend (INR)','float');

DECLARE @OpsMainTableId INT;
DECLARE @MainTableTypeId INT;
SELECT @MainTableTypeId = Table_TYP_ID FROM SSDL.SPEND_DCC_TABLE_TYP_MST where Table_TYP_code = 101
SELECT @OpsMainTableId = TableId FROM SSDL.SPEND_SSDL_TABLE WHERE TableTypeID = @MainTableTypeId AND TableName = 'OPS_MAIN';

WITH CTE AS (
select A.ColumnName,A.DataType AS correctDataType,N.DATA_TYP_NAME AS IncorrectDataType, B.TableSchemaID
from @MainTableColumnsMaster A
join ssdl.SPEND_SSDL_TableSchema B on A.ColumnName = B.ColumnName
join ssdl.SPEND_DCC_TABLE_DATA_TYP_MST N on B.DataTypeID=N.DATA_TYP_ID
where A.DataType != N.DATA_TYP_NAME and B.TABLEId=@OpsMainTableId
-- AND (N.DATA_TYP_NAME = 'int' AND A.DataType = 'bigint')
AND NOT(N.DATA_TYP_NAME = 'bit' AND A.DataType = 'boolean')
AND (
  (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'bigint')
  OR (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'varchar' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'bigint')
  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'Nvarchar' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'float' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'float' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'float' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'float' AND A.DataType = 'bigint')
  OR (N.DATA_TYP_NAME = 'float' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'float' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'float' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'Bigint' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'Bigint' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'Bigint' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'Bigint' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'Bigint' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'Bigint' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'Bigint' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'bit' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'bit' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'bit' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'bit' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'bit' AND A.DataType = 'bigint')
  OR (N.DATA_TYP_NAME = 'bit' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'bit' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'smallint' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'smallint' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'smallint' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'smallint' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'smallint' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'smallint' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'Currency' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'Currency' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'Currency' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'Currency' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'Currency' AND A.DataType = 'bigint')
  OR (N.DATA_TYP_NAME = 'Currency' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'Currency' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'int' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'int' AND A.DataType = 'date')
  OR (N.DATA_TYP_NAME = 'int' AND A.DataType = 'datetime')
  OR (N.DATA_TYP_NAME = 'int' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'int' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'int' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'date' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'date' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'date' AND A.DataType = 'bigint')
  OR (N.DATA_TYP_NAME = 'date' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'date' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'date' AND A.DataType = 'smallint')

  OR (N.DATA_TYP_NAME = 'datetime' AND A.DataType = 'float')
  OR (N.DATA_TYP_NAME = 'datetime' AND A.DataType = 'int')
  OR (N.DATA_TYP_NAME = 'datetime' AND A.DataType = 'bigint')
  OR (N.DATA_TYP_NAME = 'datetime' AND A.DataType = 'bit')
  OR (N.DATA_TYP_NAME = 'datetime' AND A.DataType = 'Currency')
  OR (N.DATA_TYP_NAME = 'datetime' AND A.DataType = 'smallint')
)
)
-- select * from cte

select distinct 'Consolidation' AS Activity, JobId,WM.JOB_NAME, A.SettingName AS StepOrTaskName, B.ColumnName, B.IncorrectDataType as ExistingDataType, B.correctDataType
from ssdl.WorkflowEventSetting AS A
JOIN CTE B ON A.SettingValue like '%'+B.ColumnName+'%' AND Eventid IN (2221,2222)
join SSDL.SPEND_DL_SA_ACIVITYWORKMASTER WM on A.JobId = WM.JOB_ID and WM.JOB_STATUS not IN('SM','C','D') and isnull(WM.IsDeleted,0) =0

select distinct 'Consolidation' AS Activity, JobId,WM.JOB_NAME, A.SettingName AS StepOrTaskName, B.ColumnName, B.IncorrectDataType as ExistingDataType, B.correctDataType
from ssdl.WorkflowEventSetting AS A
JOIN CTE B ON A.SettingValue like '%'+ B.ColumnName+'%' AND EventId IS NOT NULL
join SSDL.SPEND_DL_SA_ACIVITYWORKMASTER WM on A.JobId = WM.JOB_ID AND WM.JOB_STATUS not IN('SM','C','D') and isnull(WM.IsDeleted,0) =0
UNION
select distinct 'Profile to publish' AS Activity, JobId, WM.JOB_NAME, A.SettingName AS StepOrTaskName, B.ColumnName, B.IncorrectDataType as ExistingDataType,B.correctDataType
from ssdl.JOB_DETAILS AS A
JOIN CTE B ON A.SettingValue like '%'+B.ColumnName+'%'
join SSDL.SPEND_DL_SA_ACIVITYWORKMASTER WM on A.JobId = WM.JOB_ID AND WM.JOB_STATUS not IN('SM','C','D') and isnull(WM.IsDeleted,0) =0
UNION
SELECT DISTINCT 'Import Utility' AS Activity, A.ImportFileId AS JobId, '' AS JOB_NAME, '' AS StepOrTaskName, B.ColumnName, B.IncorrectDataType as ExistingDataType,B.correctDataType
FROM SSDL.ImportFileColumnMappingLink A
INNER JOIN CTE B ON A.TableSchemaId = B.TableSchemaID
UNION
SELECT DISTINCT 'Import Utility' AS Activity, A.ImportFileId AS JobId, '' AS JOB_NAME, '' AS StepOrTaskName, B.ColumnName, B.IncorrectDataType as ExistingDataType,B.correctDataType
FROM SSDL.ImportFileCriteria A
INNER JOIN CTE B ON A.AggregationTableSchemaId = B.TableSchemaID
UNION
SELECT DISTINCT 'Import Utility' AS Activity, C.ImportFileId AS JobId, '' AS JOB_NAME, '' AS StepOrTaskName, B.ColumnName, B.IncorrectDataType as ExistingDataType,B.correctDataType
FROM SSDL.ImportFileCriteriaConditions A
INNER JOIN CTE B ON A.DestinationColumnTableSchemaId = B.TableSchemaID
INNER JOIN SSDL.ImportFileCriteria C ON A.ImportFileCriteriaId = C.Id
UNION
SELECT DISTINCT 'Export Utility' AS Activity, A.TemplateId AS JobId, A.TemplateName AS JOB_NAME, '' AS StepOrTaskName, B.ColumnName, B.IncorrectDataType as ExistingDataType,B.correctDataType
FROM SSDL.ExportTemplateMaster A
INNER JOIN CTE B ON JSON_VALUE(A.TemplateJSON, '$.tableName') = 'OPS_MAIN'
    AND A.TemplateJSON LIKE '%' + B.ColumnName + '%'